#时序约束 create_clock -period 20.000 -name sys_clk [get_ports sys_clk] 
#IO管脚约束 
set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVCMOS33} [get_ports sys_clk] 
set_property -dict {PACKAGE_PIN U2 IOSTANDARD LVCMOS33} [get_ports sys_rst_n] 
set_property -dict {PACKAGE_PIN T1 IOSTANDARD LVCMOS33} [get_ports {key[0]}]
set_property -dict {PACKAGE_PIN U1 IOSTANDARD LVCMOS33} [get_ports {key[1]}]
set_property -dict {PACKAGE_PIN W2 IOSTANDARD LVCMOS33} [get_ports {key[2]}]
set_property -dict {PACKAGE_PIN T3 IOSTANDARD LVCMOS33} [get_ports {key[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[7]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[6]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[5]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[4]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[3]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[2]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[1]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[0]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[5]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[4]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[3]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[2]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[1]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[0]}] 
set_property PACKAGE_PIN H17 [get_ports {seg_sel[1]}] 
set_property PACKAGE_PIN H13 [get_ports {seg_sel[2]}]
set_property PACKAGE_PIN G17 [get_ports {seg_sel[3]}] 
set_property PACKAGE_PIN H18 [get_ports {seg_sel[4]}] 
set_property PACKAGE_PIN G18 [get_ports {seg_sel[5]}] 
set_property PACKAGE_PIN H15 [get_ports {seg_led[0]}] 
set_property PACKAGE_PIN G16 [get_ports {seg_led[1]}] 
set_property PACKAGE_PIN L13 [get_ports {seg_led[2]}] 
set_property PACKAGE_PIN G15 [get_ports {seg_led[3]}] 
set_property PACKAGE_PIN J15 [get_ports {seg_sel[0]}] 
set_property PACKAGE_PIN K13 [get_ports {seg_led[4]}] 
set_property PACKAGE_PIN G13 [get_ports {seg_led[5]}] 
set_property PACKAGE_PIN H14 [get_ports {seg_led[6]}] 
set_property PACKAGE_PIN J14 [get_ports {seg_led[7]}]

set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN D17} [get_ports {da_data[7]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN E17} [get_ports {da_data[6]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN F18} [get_ports {da_data[5]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN F21} [get_ports {da_data[4]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M18} [get_ports {da_data[3]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L18} [get_ports {da_data[2]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN H20} [get_ports {da_data[1]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN G20} [get_ports {da_data[0]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN N22} [get_ports da_clk]